[2024-05-28T17:47:03.178+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minutely_dag_without_catchup.print_date_task scheduled__2024-05-28T17:46:00+00:00 [queued]>
[2024-05-28T17:47:03.194+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minutely_dag_without_catchup.print_date_task scheduled__2024-05-28T17:46:00+00:00 [queued]>
[2024-05-28T17:47:03.195+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-05-28T17:47:03.225+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_date_task> on 2024-05-28 17:46:00+00:00
[2024-05-28T17:47:03.233+0000] {standard_task_runner.py:60} INFO - Started process 1873 to run task
[2024-05-28T17:47:03.237+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'minutely_dag_without_catchup', 'print_date_task', 'scheduled__2024-05-28T17:46:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/print_heure_catchup.py', '--cfg-path', '/tmp/tmpqgrkfn4s']
[2024-05-28T17:47:03.240+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask print_date_task
[2024-05-28T17:47:03.267+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T17:47:03.325+0000] {task_command.py:423} INFO - Running <TaskInstance: minutely_dag_without_catchup.print_date_task scheduled__2024-05-28T17:46:00+00:00 [running]> on host ac6c883b25f7
[2024-05-28T17:47:03.473+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minutely_dag_without_catchup' AIRFLOW_CTX_TASK_ID='print_date_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T17:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T17:46:00+00:00'
[2024-05-28T17:47:03.475+0000] {logging_mixin.py:188} INFO - 2024-05-28 17:47:03.475212
[2024-05-28T17:47:03.475+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-28T17:47:03.490+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=minutely_dag_without_catchup, task_id=print_date_task, execution_date=20240528T174600, start_date=20240528T174703, end_date=20240528T174703
[2024-05-28T17:47:03.540+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-28T17:47:03.570+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
